configfile: "config.yaml"

import os

STEMS = [f.replace(".pdb", "") for f in os.listdir(config["pdb_dir"]) if f.endswith(".pdb")]
EFS = config["energy_functions"]


rule all:
    input:
        expand(
            "results/test_distributions/{ef}/distrs_new_atom_typing.csv",
            ef=EFS,
        ),
        expand(
            "results/design_distributions/{ef}/distrs_new_atom_typing.csv",
            ef=EFS,
        )


rule gen_ref:
    input:
        pdbs=expand("{pdb_dir}/{stem}.pdb", pdb_dir=config["pdb_dir"], stem=STEMS),
    output:
        "results/crystal_ref/crystal_ref.ref",
    shell:
        "python {config[distdstr_script]} {input.pdbs} "
        "--output_dir results/crystal_ref "
        "--gen --ref {output} "
        "--use_new_atom_typing"


rule relax:
    input:
        pdb=config["pdb_dir"] + "/{stem}.pdb",
    output:
        "results/relax/{ef}/{stem}_0001.pdb",
    params:
        rosetta_bin=config["rosetta_bin"],
        rosetta_db=config["rosetta_db"],
    shell:
        "{params.rosetta_bin} "
        "-database {params.rosetta_db} "
        "-s {input.pdb} "
        "-{wildcards.ef} "
        "-crystal_refine "
        "-nstruct 1 "
        "-no_optH false "
        "-ignore_unrecognized_res "
        "-overwrite "
        "-relax:script MonomerDesign2019 "
        "-relax:cartesian true "
        "-relax:min_type lbfgs_armijo_nonmonotone "
        "-multi_cool_annealer 10 "
        "-ex1 -ex2aro "
        "-linmem_ig 10 "
        "-out:prefix results/relax/{wildcards.ef}/"


rule design:
    input:
        pdb=config["pdb_dir"] + "/{stem}.pdb",
    output:
        "results/design/{ef}/{stem}_0001.pdb",
    params:
        rosetta_scripts_bin=config["rosetta_scripts_bin"],
        rosetta_db=config["rosetta_db"],
        design_script=config["design_script"],
        surface_aa_comp_file=config["surface_aa_comp_file"],
    shell:
        "{params.rosetta_scripts_bin} "
        "-database {params.rosetta_db} "
        "-in:file:s {input.pdb} "
        "-parser:protocol {params.design_script} "
        "-out:prefix results/design/{wildcards.ef}/ "
        "-crystal_refine "
        "-read_only_ATOM_entries True "
        "-multi_cool_annealer 10 "
        "-ex1 -ex2aro -linmem_ig 10 "
        "-parser:script_vars "
        "-{wildcards.ef} "
        "surface_aa_comp_file={params.surface_aa_comp_file} "
        "relaxscript=MonomerDesign2019"


rule compute_design_distributions:
    input:
        designed_pdbs=expand(
            "results/design/{{ef}}/{stem}_0001.pdb",
            stem=STEMS,
        ),
        ref="results/crystal_ref/crystal_ref.ref",
    output:
        "results/design_distributions/{ef}/distrs_new_atom_typing.csv",
    shell:
        "python {config[distdstr_script]} {input.designed_pdbs} "
        "--ref {input.ref} "
        "--output_dir results/design_distributions/{wildcards.ef} "
        "--plot --verbose "
        "--use_new_atom_typing "
        "--allow_missing_atom_pairs"


rule compute_test_distributions:
    input:
        relaxed_pdbs=expand(
            "results/relax/{{ef}}/{stem}_0001.pdb",
            stem=STEMS,
        ),
        ref="results/crystal_ref/crystal_ref.ref",
    output:
        "results/test_distributions/{ef}/distrs_new_atom_typing.csv",
    shell:
        "python {config[distdstr_script]} {input.relaxed_pdbs} "
        "--ref {input.ref} "
        "--output_dir results/test_distributions/{wildcards.ef} "
        "--plot --verbose "
        "--use_new_atom_typing "
        "--allow_missing_atom_pairs"
